name: "Self-test: Docker check"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  self-test:
    name: Self-test Docker Check action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make mountable directory
        run: mkdir coverage

      - uses: ./docker-check
        with:
          name: 'Run `ls` from docker-check action'
          token: ${{ secrets.GITHUB_TOKEN }}
          image: alpine:latest
          flags: --volume ${{ github.workspace }}/coverage:/coverage
          command: ls
